// Sectors section · 6 bento cards · verbatim live tamazia.co.uk (TAMAZIA-13 §3)
// All cards equal weight (BD · Aman directive "no dominant card").
// Each card has 6 unique elements: numeral, icon, title+shorthand, body, regulation chips, sector-specific stat/quote.

export const sectorsContent = {
  // Backward-compatible aliases for current Sectors.astro component
  // S20 (Impl Doc v1.0) · header hierarchy reorder
  eyebrow: 'Every sector. One standard.',
  h2: 'If your industry has a regulator, {{we have already studied their guidelines.}}',
  subline: 'The sectors change. The standard does not.',
  closingLine: "International Business Law expert from King's at the core.",

  // New structured fields (used after component upgrade in Gate B)
  preambleH2: 'If your industry has a regulator, {{we have already studied their guidelines.}}',
  preambleBody: 'The sectors change. The standard does not.',
  preambleSignature: "International Business Law expert from King's at the core.",

  // All 6 cards equal size (size: 'standard'). No dominant cell.
  sectors: [
    {
      id: 'legal',
      numeral: 'I.',
      index: '01',
      size: 'standard',
      headline: 'Law Firms and the Legal Sector',
      regulatoryShorthand: 'SRA. BSB. CCBE. DIFC. ADGM. ABA. The rulebook of legal advertising, applied.',
      body: 'Built for boutique and mid-market law firms, chambers, and legal practitioners across the UK, EU, Middle East, and US. Practice area pages reviewed against SRA Standards 2019 Rules 8.7 and 8.9 and Transparency Rules 2018 for UK firms. CCBE Code and EU AI Act applied for European practitioners. DIFC, ADGM, and UAE Federal Arbitration Law 2018 applied for Middle East practice. ABA Model Rules 7.1 to 7.3 and state bar advertising rules for US firms. Partner biographies, legal directory listings, and crisis reputation management, every word reviewed before publication.',
      // Per-card pull-quote · the 6th unique element
      pullQuote: '2 million legal professionals. None can afford a compliance breach.',
      cta: 'Legal audit enquiry',
      tooltip: [
        'SRA Code of Conduct Rules 8.7 & 8.9',
        'SRA Transparency Rules 2018',
        'Bar Standards Board handbook',
        'ABA Model Rules 7.1-7.3',
        'DIFC Courts framework',
        'GDPR Art. 6 lawful basis',
        'EU AI Act · Art. 6 high-risk',
      ],
      icon: 'gavel',
    },
    {
      id: 'healthcare',
      numeral: 'II.',
      index: '02',
      size: 'standard',
      headline: 'Healthcare and Medical',
      regulatoryShorthand: 'MHRA. ASA. CQC. GMC. HIPAA. DHA. The frameworks Google reads alongside your content.',
      body: 'Built for private clinics, healthcare groups, and consultant practices across the UK, EU, Middle East, and US. UK practices reviewed against MHRA Human Medicines Regs 2012, ASA CAP Code Section 12, CQC standards, GMC Good Medical Practice 2024, and GDC standards. EU practices under MDR 2017/745 and GDPR Art. 9. Middle East practices under DHA, DOH Abu Dhabi, MoH UAE, and SFDA Saudi standards. US practices under HIPAA Privacy Rule 45 CFR 164.508, FDA 21 CFR 202, and state medical board rules.',
      pullQuote: 'More private patients from search. No regulatory exposure in any direction.',
      cta: 'Healthcare audit enquiry',
      tooltip: [
        'HIPAA Privacy Rule 45 CFR 164.508 and 164.502',
        'MHRA Human Medicines Regs 2012',
        'ASA CAP Code Section 12',
        'AMA Ethics Opinion 5.027',
        'CQC Inspection Framework',
        'Google E-E-A-T Guidelines',
        'ADA Digital Accessibility',
      ],
      icon: 'caduceus',
    },
    {
      id: 'hospitality',
      numeral: 'III.',
      index: '03',
      size: 'standard',
      headline: 'Hotels and Hospitality',
      regulatoryShorthand: 'OTA commission eliminated. Direct bookings rebuilt.',
      body: 'Booking.com and Expedia take 15 to 25% of every reservation. We rebuild the direct channel so the guest finds the property before the platform does. Built for boutique hotels, hotel groups, resorts, and heritage properties across the UK, EU, Middle East, and US. Compliance reviewed against ASA CAP Code hospitality rules, Package Travel Regulations 2018, and UK GDPR consent on booking flows. DTCM and Trakheesi for UAE properties. EU Consumer Rights Directive for cross-border bookings. £50,000 to £80,000 saved annually on a 100-room property at 70% occupancy.',
      pullQuote: '£50,000 to £80,000 saved annually on a 100-room property at 70% occupancy.',
      cta: 'Hospitality audit enquiry',
      tooltip: [
        'Schema.org Hotel structured data',
        'Google Business Profile policy',
        'Booking.com commission structure',
        'UK ASA hospitality advertising',
        'Hreflang international targeting',
        'Trakheesi UAE tourism permit',
      ],
      icon: 'bell',
    },
    {
      id: 'real-estate',
      numeral: 'IV.',
      index: '04',
      size: 'standard',
      headline: 'Real Estate, Developers and Estate Agents',
      regulatoryShorthand: 'PBSA. BTR. Residential and commercial developments. Estate agents.',
      body: 'The three highest-growth real estate marketing segments. Built for student accommodation operators, build-to-rent operators, mixed-use developers, and estate agencies across the UK, EU, Middle East, and US. International student and tenant pipelines built direct, not through aggregator platforms. Compliance reviewed against Consumer Protection from Unfair Trading Regulations 2008, Tenant Fees Act 2019, Right to Rent under Immigration Act 2014, Renters Rights Act 2024 to 2025, TPO codes, and UK GDPR. RERA Law No. 7 of 2013 and Trakheesi for UAE projects. FCA financial promotion rules for property-as-investment marketing.',
      pullQuote: 'High transaction values demand high content standards.',
      cta: 'Real estate audit enquiry',
      tooltip: [
        'SEC Regulation FD',
        'FCA COBS 4 financial promotion',
        'RERA Law No. 7 of 2013 (UAE)',
        'Trakheesi permit system',
        'DFSA Conduct of Business',
        'NYSE Listed Company Manual',
        'FINRA Rule 2210',
      ],
      icon: 'opening-bell',
    },
    {
      id: 'fb',
      numeral: 'V.',
      index: '05',
      size: 'standard',
      headline: 'Restaurants, Bars and Food & Beverage',
      regulatoryShorthand: '30,000 to 40,000 map citations. Google Maps dominance. Deliveroo dependency cut.',
      body: 'Restaurants. Pubs. Bars. Cafes. Fine dining. Nightclubs. Dark kitchens. We dominate Google Maps through 30,000 to 40,000 map citations per property, menu schema markup for rich snippets, Reserve a Table integration, review generation with incentive systems, food directory listings across 25+ platforms, and event calendar SEO.',
      pullQuote: 'Reduce Deliveroo and Uber Eats dependency the same way we reduce OTA dependency for hotels.',
      cta: 'F&B audit enquiry',
      tooltip: [
        'Schema.org Restaurant markup',
        'Google Maps citation architecture',
        "OpenTable & Resy integration",
        'Menu schema Rich Results',
        'Review platform policies',
        'ASA food advertising rules',
      ],
      icon: 'cloche',
    },
    {
      id: 'every-sector',
      numeral: 'VI.',
      index: '06',
      size: 'standard',
      headline: 'Every Sector. One Standard.',
      regulatoryShorthand: 'Schools. E-commerce. Automotive. Gyms. Executives. If it needs to rank, we build it.',
      body: 'Private schools. Universities. E-commerce brands. Luxury retailers. Car dealerships. Gyms. Spas. Wellness studios. Personal trainers. Executives and founders who need to control what Google says about them. Automotive groups. Fashion brands. If your business needs search visibility, we build it. If your industry has a rulebook, we have read it. If it does not, we make you rank faster than anyone else.',
      pullQuote: 'If your industry has a regulator, we have already studied their guidelines.',
      cta: 'Brand audit enquiry',
      tooltip: [
        'ASA CAP Code (UK)',
        'FTC Act Section 5 (US)',
        'Safeguarding content standards',
        'GDPR Art. 17 right to erasure',
        'CCPA California Privacy Rights',
        'Wikipedia Notability Guidelines',
      ],
      icon: 'compass',
    },
  ],

  // CTA strip under the grid
  ctaStrip: {
    line: 'Have any questions?',
    link: 'Continue to case studies →',
    href: '#cases',
  },
};
